export const langCode = {
    "": "auto",
    "zh": "Chinese (Simplified)",
    "en": "English",
    "jp": "Japanese",
    "th": "Thai",
    "spa": "Spanish",
    "ara": "Arabic",
    "fra": "French",
    "kor": "Korean",
    "ru": "Russian",
    "de": "German",
    "pt": "Portuguese",
    "it": "Italian",
    "el": "Greek",
    "nl": "Dutch",
    "pl": "Polish",
    "fin": "Finnish",
    "cs": "Czech",
    "bul": "Bulgarian",
    "dan": "Danish",
    "est": "Estonian",
    "hu": "Hungarian",
    "rom": "Romanian",
    "swe": "Swedish",
    "vie": "Vietname:se",
    "yue": "Cantonese (Traditional)",
    "cht": "Chinese (Traditional)",
    "bel": "Belarusian",
    "bur": "Myanmar (Burmese)",
    "fil": "Filipino",
    "hi": "Hindi",
    "ice": "Icelandic",
    "id": "Indonesian",
    "gle": "Irish",
    "kaz": "Kazakh",
    "lao": "Lao",
    "lat": "Latin",
    "ltz": "Luxembourgish",
    "mac": "Macedonian",
    "may": "Malay",
    "nep": "Nepali",
    "per": "Persian",
    "srp": "Serbian",
    "sk": "Slovak",
    "tr": "Turkish",
    "ukr": "Ukrainian",
    "uzb": "Uzbek",
    "haw": "Hawaiian",
    "mao": "Maori",
    "nor": "Norwegian",
    "epo": "Esperanto"
};