export const CONNECTION_TIMED_OUT = 'CONNECTION_TIMED_OUT';
export const BAD_REQUEST = 'BAD_REQUEST';
export const RESULT_ERROR = 'RESULT_ERROR';
export const LANGUAGE_NOT_SOPPORTED = 'LANGUAGE_NOT_SOPPORTED';
export const NO_RESULT = 'NO_RESULT';