export const SET_RESULT_BOX_SHOW_AND_POSITION = 'SET_RESULT_BOX_SHOW_AND_POSITION';
export const HIDE_RESULT_BOX = 'HIDE_RESULT_BOX';
export const INIT_RESULT_BOX_STATE = 'INIT_RESULT_BOX_STATE';
export const CALL_OUT_RESULT_BOX = 'CALL_OUT_RESULT_BOX';
export const CLOSE_RESULT_BOX = 'CLOSE_RESULT_BOX';
export const REQUEST_TO_HIDE_PANEL = 'REQUEST_TO_HIDE_PANEL';