export const ST_SET_TEXT = 'ST_SET_TEXT';
export const ST_REQUEST_START = 'ST_REQUEST_START';
export const ST_REQUEST_FINISH = 'ST_REQUEST_FINISH';
export const ST_REQUEST_ERROR = 'ST_REQUEST_ERROR';
export const ST_SET_FROM_AND_TO = 'ST_SET_FROM_AND_TO';
export const ST_INIT = 'ST_INIT';
export const ST_SET_SOURCE_FROM_TO = 'ST_SET_SOURCE_FROM_TO';