export const ADD_HISTORY = 'ADD_HISTORY';
export const UPDATE_HISTORY = 'UPDATE_HISTORY';
export const UPDATE_HISTORY_FINISH = 'UPDATE_HISTORY_FINISH';
export const UPDATE_HISTORY_ERROR = 'UPDATE_HISTORY_ERROR';
export const REMOVE_HISTORY = 'REMOVE_HISTORY';