export const SHOW_TS_RESULT_WITHOUT_RESULT_OBJECT = 'SHOW_TS_RESULT_WITHOUT_RESULT_OBJECT';
export const SHOW_TS_RESULT_WITH_TEXT = 'SHOW_TS_RESULT_WITH_TEXT';
export const SHOW_TS_RESULT_WITH_RESULT_OBJECT = 'SHOW_TS_RESULT_WITH_RESULT_OBJECT';
export const SHOW_TS_RESULT = 'SHOW_TS_RESULT';
export const HIDE_TS_RESULT = 'HIDE_TS_RESULT';
export const START_REQUEST = 'START_REQUEST';
export const FINISH_REQUEST = 'FINISH_REQUEST';
export const ERROR_REQUEST = 'ERROR_REQUEST';